# -*- coding: utf-8 -*-
"""Beroe.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Waer1s2aRLPe1ivLI-CTdMF12zeGm3rN
"""

from google.colab import files
  
  
uploaded = files.upload()

import pandas as pd
import io
  
survey = pd.read_csv(io.BytesIO(uploaded['survey.csv']))

survey

"""The dataset contains over 83,000 entries along with 5 columns."""

survey.info()

"""As seen there are some null values in every column except Response ID.  It appears that every column contains some empty values since the Non-Null count for every column is lower than the total number of rows (83439)

# Gender
"""

import matplotlib.pyplot as plt
survey_gender = survey[['Gender']]

survey_gender.groupby('Gender').size().reset_index(name='counts').sort_values(by="counts")

"""As shown above, the gender column contains multiple picks. So we can omit it for simplicity. """

survey.where(~(survey.Gender.str.contains(';', na=False)), np.nan, inplace=True)

survey_gender = survey[['Gender']]

survey_gender.groupby('Gender').size().reset_index(name='counts').sort_values(by="counts")

"""Question 1 :- Show the Graphical Representation of Gender Division"""

survey_gender['Gender'].value_counts().sort_values().plot(kind='barh')

"""Answer:- It is clearly visible that men dominate this survey and women and other genders are underrepresented in the programming community.

# Age

Question 2 :- Which age group are more involve in the programming community?
"""

survey_age = survey[['Age']]

survey_age.groupby('Age').size().reset_index(name='counts').sort_values(by="counts")

survey_age['Age'].value_counts().sort_values().plot(kind='barh')

"""Answer 2:- As seen from the bar graph, age group 25-34 and group 18-24 contribute the most in the programming community. The reason is many young people have taken up computer science as their field of study in last 2 decades.

# LanguageHaveWorkedWith

Question 3: - Which programming languages were in demand in 2021?
"""

def split_multicolumn(col_series):
    result_df = col_series.to_frame()
    options = []
    # Iterate over the column
    for idx, value  in col_series[col_series.notnull()].iteritems():
        # Break each value into list of options
        for option in value.split(';'):
            # Add the option as a column to result
            if not option in result_df.columns:
                options.append(option)
                result_df[option] = False
            # Mark the value in the option column as True
            result_df.at[idx, option] = True
    return result_df[options]
languages_worked_df = split_multicolumn(survey.LanguageHaveWorkedWith)

languages_worked_percentages = languages_worked_df.mean().sort_values(ascending=False) * 100
languages_worked_percentages

import seaborn as sns
plt.figure(figsize=(12, 12))
sns.barplot(x=languages_worked_percentages, y=languages_worked_percentages.index)
plt.title("Languages used in the 2021 year");
plt.xlabel('count');

"""Answer 3:- JavaScript and HTML/CSS were in most demand in 2021. As both are 



frontend languages and easy to learn and apply it is natural to see such trend. Pytrhon and SQL were also in demand in the year 2021.

# Years in Coding

As the yearscode is in object I have converted it into numeric for better analysis.
"""

survey['YearsCode'] = pd.to_numeric(survey.YearsCode, errors='coerce')

survey.describe()

"""Question4:- Which programming language do people with different years of coding use?"""

data_1 = survey.loc[(survey['YearsCode'] >= 1) & (survey['YearsCode'] <= 10)]
languages_worked_df = split_multicolumn(data_1.LanguageHaveWorkedWith)
languages_worked_percentages = languages_worked_df.mean().sort_values(ascending=False) * 100
import seaborn as sns
plt.figure(figsize=(12, 12))
sns.barplot(x=languages_worked_percentages, y=languages_worked_percentages.index)
plt.title("Languages used in the 2021 year for 1 to 10 years of coding experience");
plt.xlabel('count');

data_2 = survey.loc[(survey['YearsCode'] >10) & (survey['YearsCode'] <= 17)]
languages_worked_df = split_multicolumn(data_2.LanguageHaveWorkedWith)
languages_worked_percentages = languages_worked_df.mean().sort_values(ascending=False) * 100
import seaborn as sns
plt.figure(figsize=(12, 12))
sns.barplot(x=languages_worked_percentages, y=languages_worked_percentages.index)
plt.title("Languages used in the 2021 year for 10 to 17 years of coding experience");
plt.xlabel('count');

data_3 = survey.loc[(survey['YearsCode'] >17) & (survey['YearsCode'] <= 50)]
languages_worked_df = split_multicolumn(data_2.LanguageHaveWorkedWith)
languages_worked_percentages = languages_worked_df.mean().sort_values(ascending=False) * 100
import seaborn as sns
plt.figure(figsize=(12, 12))
sns.barplot(x=languages_worked_percentages, y=languages_worked_percentages.index)
plt.title("Languages used in the 2021 year for 17 or more years of coding experience");
plt.xlabel('count');

"""Answer 4: It is clearly visible that frontend languages are more in demand for all groups. But the noticable change is TypeScript's demand increases as the experience in coding increases.

Question 5: Which languages are more popular among different age groups
"""

survey['Age'].astype(str)

data_4 = survey[survey['Age']=='25-34 years old']
languages_worked_df = split_multicolumn(data_4.LanguageHaveWorkedWith)
languages_worked_percentages = languages_worked_df.mean().sort_values(ascending=False) * 100
import seaborn as sns
plt.figure(figsize=(12, 12))
sns.barplot(x=languages_worked_percentages, y=languages_worked_percentages.index)
plt.title("Languages used in the 2021 year for 25-34 years age group");
plt.xlabel('count');

data_5 = survey[survey['Age']=='18-24 years old']
languages_worked_df = split_multicolumn(data_5.LanguageHaveWorkedWith)
languages_worked_percentages = languages_worked_df.mean().sort_values(ascending=False) * 100
import seaborn as sns
plt.figure(figsize=(12, 12))
sns.barplot(x=languages_worked_percentages, y=languages_worked_percentages.index)
plt.title("Languages used in the 2021 year for 18-24 years age group");
plt.xlabel('count');

"""Answer 5:- It is clearly visible that frontend languages are more in demand for all groups. But the noticable change is TypeScript is used more by the older groups as compare to Java whereas youngsters use more Java as they are taught Java in their universities.

# SUMMARY

Question 1 :- Show the Graphical Representation of Gender Division

Conclusion :- It is clearly visible that men dominate this survey and women and other genders are underrepresented in the programming community.

Question 2 :- Which age group are more involve in the programming community?

Conclusion :- As seen from the bar graph, age group 25-34 and group 18-24 contribute the most in the programming community. The reason is many young people have taken up computer science as their field of study in last 2 decades.

Question 3: - Which programming languages were in demand in 2021?

Conclusion :- Answer 3:- JavaScript and HTML/CSS were in most demand in 2021. As both are

frontend languages and easy to learn and apply it is natural to see such trend. Pytrhon and SQL were also in demand in the year 2021.

Question4:- Which programming language do people with different years of coding use?

Conclusion:- It is clearly visible that frontend languages are more in demand for all groups. But the noticable change is TypeScript's demand increases as the experience in coding increases.

Question 5: Which languages are more popular among different age groups

Conclusion :- It is clearly visible that frontend languages are more in demand for all groups. But the noticable change is TypeScript is used more by the older groups as compare to Java whereas youngsters use more Java as they are taught Java in their universities.
"""